name: CI


on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      release-wasm:
        type: boolean
        default: false


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      
      - uses: actions/setup-python@v6
        with:
          python-version: '3.13' 
      
      - name: Build
        run: |
          mkdir cpp/build
          cd cpp/build
          cmake ..
          make
      
      - name: pytest
        run: |
          pip install \
            --index-url https://download.pytorch.org/whl/cpu \
            --extra-index-url https://pypi.org/simple        \
            -r requirements.frozen.txt
          ./run_tests.sh

  build-wasm:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      
      - uses: mymindstorm/setup-emsdk@v14
        with:
          version: 3.1.69
          actions-cache-folder: 'emsdk-cache'

      - name: Deno
        run: |
          ./deno.sh task cache
      
      - name: Build
        run: |
          emcc -v
          mkdir cpp/build-wasm
          cd cpp/build-wasm
          emcmake cmake ..                      \
            -DCMAKE_BUILD_TYPE=Release          \
            -DCMAKE_VERBOSE_MAKEFILE=ON
          emmake make
          ../../deno.sh bundle --minify --outdir=./bundle ../carrot-wasm-postprocessing.ts

      - name: Test
        run: |
          ./run_tests_deno.sh
      
      - name: Archive JS module
        uses: actions/upload-artifact@v4
        with:
          name: modules
          path: |
            cpp/build-wasm/bundle/carrot-wasm-postprocessing.js
            cpp/carrot-wasm-postprocessing.d.ts
          if-no-files-found: error

      - name: Release
        if: ${{ github.event.inputs.release-wasm == 'true' }}
        run: |
          TAGNAME=v$(date +%F)
          echo $TAGNAME
          # note: backup file before git checkout
          mkdir tmp
          cp cpp/carrot-wasm-postprocessing.d.ts tmp/
          cp cpp/build-wasm/bundle/carrot-wasm-postprocessing.js tmp/
          #
          git fetch origin wasm-releases
          git checkout wasm-releases
          cp tmp/* ./
          rm -r tmp
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ./carrot-wasm-postprocessing.*
          git commit -m "$TAGNAME"
          git tag --force $TAGNAME
          git push origin wasm-releases
          git push origin --tags


